/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DaqDigIOAccess_DaqDigIOAccess */

#ifndef _Included_DaqDigIOAccess_DaqDigIOAccess
#define _Included_DaqDigIOAccess_DaqDigIOAccess
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: SIM_MODE */
#undef DaqDigIOAccess_DaqDigIOAccess_LANES
#define DaqDigIOAccess_DaqDigIOAccess_LANES 12L
/* Inaccessible static: daqIOAccess */
/*
 * Class:     DaqDigIOAccess_DaqDigIOAccess
 * Method:    allocateResources
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DaqDigIOAccess_DaqDigIOAccess_allocateResources
  (JNIEnv *, jobject);

/*
 * Class:     DaqDigIOAccess_DaqDigIOAccess
 * Method:    freeAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DaqDigIOAccess_DaqDigIOAccess_freeAll
  (JNIEnv *, jobject);

/*
 * Class:     DaqDigIOAccess_DaqDigIOAccess
 * Method:    testDaqDigIOCard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DaqDigIOAccess_DaqDigIOAccess_testDaqDigIOCard
  (JNIEnv *, jobject);

/*
 * Class:     DaqDigIOAccess_DaqDigIOAccess
 * Method:    testFireGateOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DaqDigIOAccess_DaqDigIOAccess_testFireGateOff
  (JNIEnv *, jobject);

/*
 * Class:     DaqDigIOAccess_DaqDigIOAccess
 * Method:    testFireGateOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DaqDigIOAccess_DaqDigIOAccess_testFireGateOn
  (JNIEnv *, jobject);

/*
 * Class:     DaqDigIOAccess_DaqDigIOAccess
 * Method:    testReadLaneSignals
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DaqDigIOAccess_DaqDigIOAccess_testReadLaneSignals
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
